### ISSUE TITLE
Add Prim's Kruskal And Dijkstra’s shortest path algorithm

### ISSUE THREAD

**Issue by Kushal-W** [Kushal-W/AlgoInC#1]
Add These algorithm code.
Rules
1. Language should be C or C++
2. Code should be tested.

**Comment by chhavi-rana** [comment]
Please assign this issue to me.

**Comment by Aditya-wani02** [comment]
I would like to work on it.
plz assign it to me

**Comment by Arka90** [comment]
I would like to contribute to this project please assign it to me

**Comment by Kushal-W** [comment]
This is not accepted in Hacktoberfest
